language: node_js
node_js:
  - "10"
notifications:
  email: false
script:
  - echo Hello
  - bash ./script.sh
deploy:
  provider: script
  script: ./script.sh
  skip_cleanup: true
  on:
    branch: master
