language: minimal
#language: node_js
#node_js:
#  - "12"
notifications:
  email: false
branches:
  only: 
    - master
script:
  - echo Hello
deploy:
  provider: script
  script: ./deploy-release-tag.sh
  on:
    branch: master
    tags: false
env:
  global:
    # secure: "LZkJtSrPwF9s7ORI6E8UW/zxDyLq3uhOHZ+vG44lb4IzHo6WrGw8RTgDppywQjIvdEOTqwC4Cmt0VxKjVhLx99XEESj7fNnUuXRwdRIygeMU8JSp0FOdnNuIYBHxjdbPVKjIK0Ffzj7rCkxlLUj2RFUlrX/vTuUH8bmU77YX1A9erc0N66KC7Xlc97Xv3fDd/dTLeN8NRuhkapN/sbI9VgGuuj+/+CYNVR04jbopw8mOF4HQlbdK0MmAU5S2XP6wQ41Oxyl3AwkuwzL5P9L8Jkff3Hqf621ckzA2/52pWuSE2MgG/rBBDw99cs7OOPckzOCKZ3BFYFJodg8WGoGxoBIIdN8g3iBErVERFRPiCBRf8gTJDFKuHBM5FVGR7NqOxuh1fb6Ttbb6x31wuuT2EDoCcBxxB6AVAGb/IqJZ3Q/nbPctBKdU7maobhUs/IstjCgFSf/dtOBTQjAYYQFiRGvj/ywsyK6/dK5VzYv8lC+Z6s0q9honvWAfppOnj+26MTjzOPNRfgaOxgB0oC2VuJ0wOF7QI91Io4SAtrmqNpjHVHyqcva32HBseDLz/2Z0lMI7S6Y5X1orQ3q2bP9LOXFQVwX661uIgTT4iXP1Pj4+7eU6tBBIGPurTHm+KtK+8TyfbigenyXwE32BmyZIDKboCYoBBgPYHUDb4mfn6os="
    - DEPLOY_VERSION_FILE="src/zif_abapgit_version.intf.abap"
    - DEPLOY_VERSION_CONST="gc_abap_version"
    - ENCRYPTION_LABEL="d04247868aac"
