language: minimal
#language: node_js
#node_js:
#  - "12"
notifications:
  email: false
script:
  - echo Hello
  - ./script.sh
deploy:
  provider: script
  script: ./script.sh
  skip_cleanup: true
  on:
    branch: master
