language: minimal
#language: node_js
#node_js:
#  - "12"
notifications:
  email: false
script:
  - echo Hello
deploy:
  provider: script
  script: ./deploy-release-tag.sh
  skip_cleanup: true
  on:
    branch: master
    tags: false
